// "use client";
import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Buttons from "./components/organisms/Buttons";

export const metadata: Metadata = {
  title: "Tutorial",
  description: "Generated by naeun",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + "topics", {
    cache: "no-store",
  });
  const topics = await resp.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic: any) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Buttons />
      </body>
    </html>
  );
}
